import fs from 'node:fs/promises';
import path from 'node:path';
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';
import type { AggregateMetrics } from '@/features/performance-hub/types';
import type { ChartDataPoint } from '@/features/performance-hub/types';
import type { TimeRange } from '@/features/performance-hub/actions/fetchMetrics';
import type { CockpitPlatform } from '@/features/performance-hub/lib/cockpit-platform';

const PAGE_W = 595;
const PAGE_H = 842;
const M = 48;

const BG = rgb(0.047, 0.027, 0.047); // #0c070c
const GOLD = rgb(0.745, 0.627, 0.259); // #bea042
const VIOLET = rgb(0.612, 0.439, 0.722); // #9c70b2-ish
const TEXT = rgb(0.92, 0.92, 0.94);
const MUTED = rgb(0.55, 0.52, 0.58);
const LINE = rgb(0.18, 0.12, 0.18);

function toWinAnsi(text: string): string {
  return text
    .replace(/[\u2018\u2019\u0060]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/\u2026/g, '...')
    .replace(/[^\x20-\xFF\n\r\t]/g, '');
}

function wrapLine(font: PDFFont, text: string, size: number, maxW: number): string[] {
  const clean = toWinAnsi(text);
  const words = clean.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = '';
  for (const w of words) {
    const trial = cur ? `${cur} ${w}` : w;
    if (font.widthOfTextAtSize(trial, size) <= maxW) {
      cur = trial;
    } else {
      if (cur) lines.push(cur);
      cur = w;
    }
  }
  if (cur) lines.push(cur);
  return lines.length ? lines : [''];
}

function drawFooter(page: PDFPage, font: PDFFont, pageNum: number) {
  page.drawRectangle({ x: 0, y: 0, width: PAGE_W, height: 34, color: rgb(0.06, 0.04, 0.07) });
  page.drawText('Generated by Madmonos AI', {
    x: M,
    y: 12,
    size: 8,
    font,
    color: MUTED,
  });
  page.drawText(`mono Report · ${pageNum}`, {
    x: PAGE_W - M - font.widthOfTextAtSize(`mono Report · ${pageNum}`, 8),
    y: 12,
    size: 8,
    font,
    color: MUTED,
  });
}

export async function renderMonoReportPdf(input: {
  tenantName: string;
  range: TimeRange;
  cockpit: CockpitPlatform;
  metrics: AggregateMetrics;
  chart: ChartDataPoint[];
  narrative: string;
  poweredLine: string;
}): Promise<Uint8Array> {
  const { tenantName, range, cockpit, metrics, chart, narrative, poweredLine } = input;
  const doc = await PDFDocument.create();
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - M;

  page.drawRectangle({ x: 0, y: 0, width: PAGE_W, height: PAGE_H, color: BG });

  // Header glass bar
  page.drawRectangle({ x: 0, y: PAGE_H - 120, width: PAGE_W, height: 120, color: rgb(0.11, 0.06, 0.11) });
  page.drawRectangle({ x: 0, y: PAGE_H - 3, width: PAGE_W, height: 3, color: GOLD });

  try {
    const logoPath = path.join(process.cwd(), 'public', 'madmonos-logo-optimized.png');
    const bytes = await fs.readFile(logoPath);
    const png = await doc.embedPng(bytes);
    const lw = 44;
    const lh = (png.height / png.width) * lw;
    page.drawImage(png, { x: M, y: PAGE_H - 100, width: lw, height: lh });
  } catch {
    // skip logo embed
  }

  page.drawText('mono Report', {
    x: M + 52,
    y: PAGE_H - 56,
    size: 22,
    font: bold,
    color: TEXT,
  });
  page.drawText(poweredLine, {
    x: M + 52,
    y: PAGE_H - 78,
    size: 9,
    font: regular,
    color: MUTED,
  });

  y = PAGE_H - 140;
  page.drawText(toWinAnsi(tenantName), { x: M, y, size: 14, font: bold, color: TEXT });
  y -= 22;
  page.drawText(`Range: ${range}   ·   Cockpit: ${cockpit}`, { x: M, y, size: 10, font: regular, color: MUTED });
  y -= 18;
  page.drawText(
    `Period ${metrics.dateRange.from} → ${metrics.dateRange.to}`,
    { x: M, y, size: 9, font: regular, color: MUTED },
  );
  y -= 28;

  page.drawText('Executive summary', { x: M, y, size: 12, font: bold, color: GOLD });
  y -= 16;
  page.drawRectangle({ x: M, y: y - 92, width: PAGE_W - 2 * M, height: 92, color: rgb(0.09, 0.05, 0.09) });
  page.drawRectangle({
    x: M,
    y: y - 92,
    width: PAGE_W - 2 * M,
    height: 92,
    borderColor: LINE,
    borderWidth: 0.6,
  });

  const rows: string[] = [
    `ROAS (current)     ${metrics.roas.current.toFixed(2)}`,
    `Spend (current)    ${metrics.spend.current.toFixed(2)}`,
    `Revenue (current)  ${metrics.revenue.current.toFixed(2)}`,
    `CTR %              ${metrics.ctr.current.toFixed(2)}`,
    `Conversions        ${metrics.conversions.current.toFixed(0)}`,
  ];
  let ry = y - 14;
  for (const line of rows) {
    page.drawText(toWinAnsi(line), { x: M + 12, y: ry, size: 10, font: regular, color: TEXT });
    ry -= 14;
  }
  y = ry - 20;

  page.drawText('Spend trend (tabular)', { x: M, y, size: 12, font: bold, color: VIOLET });
  y -= 14;
  const slice = chart.slice(-16);
  for (const row of slice) {
    const line = `${row.date}   meta ${row.meta.toFixed(0)}   google ${row.google.toFixed(0)}   tiktok ${row.tiktok.toFixed(0)}`;
    if (y < 80) {
      page = doc.addPage([PAGE_W, PAGE_H]);
      page.drawRectangle({ x: 0, y: 0, width: PAGE_W, height: PAGE_H, color: BG });
      y = PAGE_H - M;
    }
    for (const wl of wrapLine(regular, line, 8.5, PAGE_W - 2 * M)) {
      page.drawText(wl, { x: M, y, size: 8.5, font: regular, color: TEXT });
      y -= 11;
    }
  }

  y -= 10;
  page.drawText('Strategic summary (monoAI)', { x: M, y, size: 12, font: bold, color: GOLD });
  y -= 16;

  const body = narrative.trim() || '—';
  for (const para of body.split(/\n+/)) {
    const wrapped = wrapLine(regular, para, 10, PAGE_W - 2 * M);
    for (const line of wrapped) {
      if (y < 90) {
        page = doc.addPage([PAGE_W, PAGE_H]);
        page.drawRectangle({ x: 0, y: 0, width: PAGE_W, height: PAGE_H, color: BG });
        y = PAGE_H - M;
      }
      page.drawText(line, { x: M, y, size: 10, font: regular, color: TEXT });
      y -= 13;
    }
    y -= 6;
  }

  doc.getPages().forEach((p, i) => drawFooter(p, regular, i + 1));
  return doc.save();
}
